FROM determinedai/environments:cuda-10.1-pytorch-1.4-tf-2.2-gpu-0.4.0
RUN apt-get update && apt-get install -y libsm6 libxext6 libxrender-dev
RUN pip install stable-baselines opencv-python cloudpickle==0.5.5
